baseurl = "http://theneuralbit.com/"
languageCode = "en-us"
title = "the neural bit"
theme = "theneuralbit"

[Params]
    tagline = "derp"
    author = "Brian Hulette"
    description = "derpity"
    logoBig = "/images/osprey-logo.png"
    logoSmall = "/images/osprey-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    twitter = "BrianHulette"
    linkedin = "brian-hulette"
    github = "theneuralbit"
    email = "hulettbh@gmail.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
